FROM node:20

RUN apt-get update && apt-get install -y default-jre

# Create app folder
WORKDIR /app

# Copy everything
COPY . .

# Move into functions directory and install
WORKDIR /app/functions
RUN npm install

# Start emulator
CMD ["npm", "run", "shell"]